version: '3'

services:
  service-broker:
    build:
      context: ./service-broker
      dockerfile: ./service-broker.dockerfile
    restart: always
    ports:
      - "8000:3000"
    deploy:
      mode: replicated
      replicas: 1
  # dashboard:
  #   build:
  #     context: ./dashboard
  #     dockerfile: ./dashboard.dockerfile
  #   restart: always
  #   ports:
  #     - "8001:3001"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
